### ISSUE TITLE
Unable to use multi-lingual model

### ISSUE THREAD

**Issue by tomaszchorazy** [vivekuppal/transcribe#115]
I have `base.pt` model downloaded and trying to pass it as a parameter during execution with `-m base` but I'm getting:
`Could not find the transcription model file: base.en.pt`
Why it's trying to enforce english model?

**Comment by abhinavuppal1** [comment]
A couple of questions will help with moving forward

- Are you using the code and executing using python
OR
- Have you downloaded the binary and executing the binary

In either case
- Please share a screenshot or output that you see on the command line window
- Please share the version of github code or binary (link) being used

**Comment by tomaszchorazy** [comment]
I'm using binary.
I think I resolved the issue. I've downloaded `base.en.pt` also and now I have both models. It looks that english model is required always. 
After changing the language in UI it's transcribing using my language (Polish). One thing worth to mention:
We often use single English phrases in Polish during technical conversations. The transcription clearly cannot cope with this

**Comment by vivekuppal** [comment]
Glad that things worked out for you. 
I believe this issue has been resolved in the latest code base. Would be great to get feedback on this once the new binaries are published.
For cases where multi lingual support in the same conversation is required, might want to attempt and use ``--api`` option.
That uses the whisper online API and might be better for that use case.

**Comment by vivekuppal** [comment]
With the [latest release](https://drive.google.com/file/d/14-rULM5ov6RQ5ksicW5cNJJgckSD0Co9/view?usp=sharing) that was just published by default we download the multi lingual model.
I believe this issue should not happen any more.
Also by default tiny model is downloaded because it is the smallest.

Can use the argument `-m` to download a different model.

```
E.g. transcribe.exe -m base 
```

base model is larger in size than tiny model, but gives better transcription results. For a list of all options please see help

```
transcribe.exe -h
```

**Comment by vivekuppal** [comment]
Please re-open if there are further questions.
